<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Release</Configurations>
    <Version>1.4.1</Version>
    <Company>Atesh Entertainment Inc.</Company>
    <Product>BindableProperties</Product>
    <Authors>The team members are listed in README.md file on project web page.</Authors>
    <PackageLicenseUrl>http://unlicense.org</PackageLicenseUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>Property, BindablePropery, Binding</PackageTags>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <FileVersion>1.4.1.0</FileVersion>
    <PackageProjectUrl>https://bitbucket.org/XtroTheArctic/bindableproperties</PackageProjectUrl>
    <RepositoryUrl>git@bitbucket.org:XtroTheArctic/bindableproperties.git</RepositoryUrl>
    <Description>BindableProperties is a class library which provides a bindable properties system similar to "Microsoft WPF Dependency Properties" and "Xamarin Bindable Properties" systems. The biggest difference of BindableProperties to those systems is that it does NOT depend on any other 3rd party platform or framework such as Microsoft WPF and Xamarin so it can be used by almost any kind of .NET projects.</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin</OutputPath>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <NoWarn />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
